- name: add epel-release repo
  yum:
    name: epel-release
    state: present

- name: install nginx
  yum: 
    name: nginx
    state: present
  notify:
    - start nginx
    - enable nginx
- restart nginx

- name: insert index page
  template:
    src: index.html
    dest: /usr/share/nginx/html/index.html
  notify:
    - reload nginx
