---
- name: Install nginx
  hosts: nginx
  become: true

  tasks:
  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: Install nginx
    yum:
      name: nginx
      state: present
    notify:
     - start nginx
     - enable nginx
  - restart nginx

  - name: Insert Index Page
    template:
      src: index.html
      dest: /usr/share/nginx/html/index.html
    notify:
     - reload nginx

  - name: Start NGiNX
    service:
      name: nginx
      state: started

