- name: enable nginx
  systemd:
    name: nginx
    daemon_reload: yes
    enabled: yes

- name: start nginx
  systemd:
    name: nginx
    daemon_reload: yes
    state: started

- name: restart nginx
  systemd:
    name: nginx
    daemon_reload: yes
    state: restarted

- name: reload nginx
  systemd:
    name: nginx
    daemon_reload: yes
    state: reloaded
