---
- name: Ensure the VM is defined
  virt:
    name: "{{ libvirt_vm_name }}"
    command: define
    xml: "{{ lookup('template', 'vm.xml.j2') }}"

- name: Ensure the VM is running and started at boot
  virt:
    name: "{{ libvirt_vm_name }}"
    autostart: true
    state: running
