---
- name: Create libvirt VM
  hosts: all
  roles:
    - role: stackhpc.libvirt-vm
      libvirt_vm_state: present
      libvirt_vm_name: 'test'
      libvirt_vm_memory_mb: 1024
      libvirt_vm_vcpus: 1
      libvirt_vm_volumes:
        - name: 'data'
          device: 'disk'
          format: 'qcow2'
          capacity: '400gb'
          pool: 'my-pool'
      libvirt_vm_interfaces:
        - network: 'virt_datacentre'


